### ISSUE TITLE
Raw OSM Data Save Option

### ISSUE THREAD

**Issue by myrisee** [vvoovv/blender-geo#255]
Hello

I'm using the Blender-OSM Premium for creating real world terrains on Unity3d. Most of the times I'm suffering from getting the raw OSM road data from the openstreetmap.org because of node limit. I need to create roads and paths in Unity, not on Blender so saving raw osm data option would be perfect for me. 

Thanks

**Comment by vvoovv** [comment]
Hi @myrisee,

There is no node limit if you download OSM data using the Blender-OSM addon. Set the data source to _server_ rather than _file_. Then follow the instructions in the [documentation](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#openstreetmap-import-from-the-server). Note the name of the imported collection. It should something like _map_12.osm_. The download OSM file is stored at _[data folder from the addon preferences]/osm/map_12.osm_

**Comment by myrisee** [comment]
Woow i didnt know OSM files stored in cache thanks for the answer. It solved my problem
