### ISSUE TITLE
Seeing 2 story buildings

### ISSUE THREAD

**Issue by TArlow** [vvoovv/blender-geo#266]
Hi, just purchased blender OSM. I live in a 2 story home in a rural area. With the addon I can import the terrain and map successfully, but none of the buildings show up. Some of the larger local buildings do however - I tried increasing the level height, but still cannot visualize 3D buildings from my neigborhood. Is this something I’m doing wrong, or is it a limitation of the addon/rural area/height of my home? Thanks

**Comment by vvoovv** [comment]
Hi @TArlow,

I’ve just sent you a request via email for the coordinates of the area where the buildings are missing. The coordinates are needed to check the import out.

**Comment by vvoovv** [comment]
I examined your area of interest. It contains only 4 buildings in the park.

The problem you are experiencing is due to the nature of OpenStreetMap. It's a collaborative wiki-alike mapping project where everyone can contribute. If a building isn't there, it means nobody mapped it so far at OpenStreetMap.

It's quite easy to start mapping at OpenStreetMap.
Zoom to your area of interest at https://osm.org and press the "Edit" tab. An interactive tutorial will be offered.

The desired tags for the buildings are _building:levels_ for the number of storeys, _roof:height_ for the roof height and _roof:shape_ for the roof shape.

**Comment by TArlow** [comment]
Hi,

I joined OSM and added the buildings in the neighborhood, works great,
thanks so much!

Tim
