### ISSUE TITLE
Mapbox images do not load 

### ISSUE THREAD

**Issue by eusirenko** [vvoovv/blender-geo#283]
I could import terrain very easily. However when I select Mapbox terrain or Mapbox Satelite the import starts, but gives me this error. The public token was added in the preferences. 
I am using Blender 3.0 and premium version of the add-on.
![image](https://user-images.githubusercontent.com/99347372/153235929-97e4431a-54d6-4e52-9315-34bb655a9032.png)

**Comment by vvoovv** [comment]
Regarding the Mapbox Streets.

Mapbox deprecated referring to their map via mapbox.streets. However it's possible to refer to it via a URL that starts with mapbox://

Below is a temporary solution. The problem will be fixed in the next release of the addon. I hope it will happen in March.

Set "Overlay" to "Custom URL".
In the next field below the sentence "Paste overlay URL here:" paste: mapbox://styles/mapbox/streets-v11

Sorry for the inconvenience.

**Comment by vvoovv** [comment]
Does Mapbox Satellite work for you?

**Comment by eusirenko** [comment]
Mapbox Satellite - yes

**Comment by vvoovv** [comment]
The problem with the Mapbox Streets has been fixed. Please update the addon.
