### ISSUE TITLE
Strange Terrain Issue

### ISSUE THREAD

**Issue by Antapino** [vvoovv/blender-geo#291]
Hello! Im experiencing an issue with the terrain, am i doing something wrong or is this an issue?

![Screenshot_2](https://user-images.githubusercontent.com/66879361/158888299-d10ee263-31ea-4f77-9358-df9ed32521ca.png)

**Comment by vvoovv** [comment]
Hi @Antapino 

I'd like to reproduce your problem. What are the coordinates of your area of interest?

**Comment by Antapino** [comment]
-80.66312,28.57374,-80.61201,28.60562
 It imports the OpenStreetMap, but not the terrain

**Comment by vvoovv** [comment]
Hi @Antapino 

Thank you for your feedback.

I was able to reproduce the problem. The issue is due to the underlying terrain data.

Please refer to the terrain data set description used by the addon:
https://github.com/tilezen/joerd/blob/master/docs/data-sources.md#known-issues
Many classical DEM and LIDAR related issues occur in terrain tiles. It is not uncommon to see large variations in elevation in areas with large buildings and other such structures. Resampling and merging artifacts are also observed along coastlines (where different datasets are seamed together).

I'll try to replace those spikes with some meaningful values in the code. I'll let you know once the fix is ready.

For now I'd suggest to quickly fix the terrain in the EDIT mode. Select the vertices at the top of the spikes in the wireframe mode using the box select. Set z-coordinate of the selected vertices to some meaningful value.

**Comment by Antapino** [comment]
Thanks!
