### ISSUE TITLE
Selection rectangle is tiny!

### ISSUE THREAD

**Issue by e170385** [vvoovv/blender-geo#300]
I was fed up by blender GIS crappy heightmaps and we bought this. Now I'm even more annoyed, since OSM seems to have an awfully tiny selection box compared to GIS. Is there no tiling or anything? I mean I can't even select one small country like Austria..? How can this be worse than a free addon?

**Comment by vvoovv** [comment]
Hi @e170385

Thank you for using our addon!

The limit of the area size is set intentionally, since Blender can't process millions of buildings.

If you are interested in importing the terrain and satellite imagery for the whole Austria or another country, you can enter the coordinates manually in the addon panel.

We strongly recommend you setting a smaller reduction factor in the _Vertex reduction_ options in the _Terrain_ panel to get an affordable size for the terrain mesh.

![image](https://user-images.githubusercontent.com/613295/169526573-5e979133-fa46-4ae0-abf8-4be25b75146b.png)
