### ISSUE TITLE
Issue importing Terrain - causing spikes

### ISSUE THREAD

**Issue by ostokes1** [vvoovv/blender-geo#337]
I am trying to download a region of terrain around Boston, MA and keep getting spikes around the downtown area. All I am doing is adding the coordinates I need, changing the dropdown to terrain, and importing. Not sure what I am doing wrong. Thank you for the help!

![Screenshot 2023-02-08 215019](https://user-images.githubusercontent.com/31577900/217705413-d7293fcc-a7c0-4fde-9c9f-65007f70d856.jpg)
![Screenshot 2023-02-08 215043](https://user-images.githubusercontent.com/31577900/217705422-0dc3a209-33e8-4d7c-a7cb-b9a0c24b799b.jpg)

**Comment by vvoovv** [comment]
Hi @ostokes1 

This is a known issue due to the underlying terrain data.

Please refer to the terrain data set description used by the addon:
https://github.com/tilezen/joerd/blob/master/docs/data-sources.md#known-issues
Many classical DEM and LIDAR related issues occur in terrain tiles. It is not uncommon to see large variations in elevation in areas with large buildings and other such structures. Resampling and merging artifacts are also observed along coastlines (where different datasets are seamed together).

For now I'd suggest to quickly fix the terrain in the EDIT mode. Select the vertices at the top of the spikes in the wireframe mode using the box select. Set z-coordinate of the selected vertices to some meaningful value.
