### ISSUE TITLE
Terrain import is incorrect

### ISSUE THREAD

**Issue by TalkaboutCheese** [vvoovv/blender-geo#349]
Hello,

I recently tried to make a model of Boston, MA USA but found that the terrain import had a strange pillarlike defect. After looking through a few forums, I can't seem to find anyone with a similar issue. I've attached screenshots of both blender and the area I'm selecting. 

Could anybody help me understand what's going on here?

Thanks

Coords:

                 
                  42.37034
-71.07536                    -71.04558
                  42.34890

![Screenshot 2023-04-28 192753](https://user-images.githubusercontent.com/132110669/235269373-25291136-2ca8-41db-9100-1ecd1b4e6f8d.png)
![Screenshot 2023-04-28 192714](https://user-images.githubusercontent.com/132110669/235269375-1ee28b45-1b12-4f86-afc6-688331a8bee2.png)

**Comment by vvoovv** [comment]
Hi @TalkaboutCheese 

This is a known issue due to the underlying terrain data.

Please refer to the terrain data set description used by the addon:
https://github.com/tilezen/joerd/blob/master/docs/data-sources.md#known-issues
Many classical DEM and LIDAR related issues occur in terrain tiles. It is not uncommon to see large variations in elevation in areas with large buildings and other such structures. Resampling and merging artifacts are also observed along coastlines (where different datasets are seamed together).

For now I'd suggest to quickly fix the terrain in the EDIT mode. Select the vertices at the top of the spikes in the wireframe mode using the box select. Set z-coordinate of the selected vertices to some meaningful value.

**Comment by TalkaboutCheese** [comment]
Hi @vvoovv 

Thank you so much for the response. I wanted to make sure this wasn't something I was doing incorrectly. I will do what I can do to fix the terrain issues on my own.

Thanks again.
