### ISSUE TITLE
Buildings' height not imported when they have building:parts inside

### ISSUE THREAD

**Issue by ccamara** [vvoovv/blender-geo#60]
I have realized that some buildings are not imported when they have a building:part inside with different height (like these ones http://www.openstreetmap.org/way/476392278, http://www.openstreetmap.org/relation/6956389 or http://www.openstreetmap.org/way/474901364, outlined in the screenshot below)

This is how they look in F4 map:

![f4map demo interactive 3d map](https://cloud.githubusercontent.com/assets/706549/23396627/fbcb5f36-fd94-11e6-8082-97ef5f186c1e.png)

And this is how they look in blender (not imported at all):
![screenshot_20170228_090617](https://cloud.githubusercontent.com/assets/706549/23396706/50b1c83c-fd95-11e6-934a-c5540a4d135c.png)

I've found a workaround: just by adding `building:part=yes` to buildings' outline will make the trick (see screenshot below). Unfortunately it doesn't make sense in OSM, and other editors may decide to remove such tag.

![screenshot_20170228_092045](https://cloud.githubusercontent.com/assets/706549/23397100/41e9f78c-fd97-11e6-80a1-8ad0671d8ac9.png)

**Comment by vvoovv** [comment]
The problem was discussed at the OSM forum several weeks ago: [Can a closed way be tagged with both: "building", "building:part"?](https://forum.openstreetmap.org/viewtopic.php?id=56776)

blender-osm works in accordance with [Simple 3D Buildings](https://wiki.openstreetmap.org/wiki/Simple_3D_buildings#Building_parts):

`Note that a building outline area containing OSM ways or relations tagged with building:part=* is not considered for 3D rendering.`

So the behavior of F4 maps is incorrect in those cases.

What are the correct ways to fix the problem?

But first a general note. The tags _building:levels_ and _height_ for a building outline reflects the largest values for all building parts. So if there is a bulding part with _building:levels=9_ and that is the largest value for all building parts, then the building outline must have _building:levels=9_ as well.

There are a number of alternatives if a building outline is also to serve as the building part:

1) Add a relation _building:part=yes_ referencing the members of the building outline (if the outline is a relation) or the way for the outline (if the outline is a single way). It appears to be the simplest correct solution for all possible cases. That is how I fixed http://www.openstreetmap.org/way/476392278 and http://www.openstreetmap.org/relation/6956389

2) Add _building:part=yes_ to the building outline. However in most case the height of a part is not equal to the total height of the building. So this solution is rarely correct. Nevertheless I preserved this solution for http://www.openstreetmap.org/way/474901364

3) If the building outline is a single way, duplicate the way for the building part. This solution creates overlapping ways. So I don't recommend this solution.

**Comment by ccamara** [comment]
Thanks for the explanation (with fixes in OSM changesets!): I'll read the provided links to learn the justification behind that.

Since I am assuming this addon works as expected I am closing this issue.
