### ISSUE TITLE
Not all buildings are included

### ISSUE THREAD

**Issue by MMorpheus1** [vvoovv/blender-geo#73]
I just figured out, that the Add-On doesn't include all buildings, which are modeled in OSM.

One example:
Attached are two pictures. The first called "OSM" shows the same area based on an online-Viewer  of OSM buildings [https://osmbuildings.org/?lat=48.1326&lon=11.58089&zoom=16.6&rotation=1&tilt=31]
The second shows my result in blender. 
The major part of the red "L-shaped" building is missing and the main parts of the big building on the island is missing.
![osm](https://cloud.githubusercontent.com/assets/27648257/26529877/3ce080a8-43c9-11e7-998e-a2a2690368a4.jpeg)
![blender](https://cloud.githubusercontent.com/assets/27648257/26529876/3cde3b86-43c9-11e7-8a8d-fea3b2526f2c.jpeg)

coordinates are:
lon. 11.5795898 11.6015 lat. 48.122101 48.1367666

**Comment by vvoovv** [comment]
It was due to the wrong mapping in OSM. I fixed it in the OSM database. Also I added more details for those buildings.

Please import that area from the server again.

**Comment by vvoovv** [comment]
Here are additional details.

The blender-osm addon creates buildings in accordance with the [Simple 3D Buildings](http://wiki.openstreetmap.org/wiki/Simple_3D_buildings) specification of OpenStreetMap. As mentioned in the previous message, the buildings were not shown due to wrong mapping that didn't comply with the specification.

I wouldn't advise you to use osmbuildings.org as a reference point, since it doesn't support the Simple 3D Buildings specification to the full extent. Here is how the Moscow Kremling looks like in osmbuildings.org:
![image](https://cloud.githubusercontent.com/assets/613295/26589215/2021a832-4560-11e7-92e8-b7ef4df410f8.png)

The most of building parts are missing. Compare it with the result of blender-osm.

In general, it's not that difficult to learn how to map 3D features in OpenStreetMap. [Here](https://github.com/vvoovv/blender-osm/wiki/OpenStreetMap) are good tutorials to guide you from simple mapping concepts to 3D mapping in OSM. 

I hope you will be able to fix yourself wrong 3D mapping in OSM.

**Comment by MMorpheus1** [comment]
Thanks a lot for your help, once again!

I'm sorry I blamed the Add-on for the mistake, while it was in the OSM Database!
I am trying to understand OSM mapping more and more and already fixed some issues of 3D mapping I've come across. Your advice on osmbuildings.org and your tutorials were also greatly appreciated!

Keep up your great work!

**Comment by vvoovv** [comment]
Thank your feedback!

Probably the key thing to remember about 3D mapping is that a building outline (tagged with the _building_ tag) won't be rendered if there is at least one building part (tagged with the _building:part_ tag) located inside the building outline.
