### ISSUE TITLE
Type error when importing buildings with terrain

### ISSUE THREAD

**Issue by tanvach** [vvoovv/blender-geo#79]
I'm seeing an issue where the plugin would fail if I import buildings in San Francisco with terrain. The import works fine without terrain.

Here's an example of an area in San Francisco imported correctly with buildings only:
-122.48280,37.75904,-122.37740,37.81439

<img width="2032" alt="screen shot 2017-07-04 at 10 36 26 am" src="https://user-images.githubusercontent.com/729913/27839498-8349924c-60a6-11e7-8339-af1c1d7f86f1.png">

Turning on terrain I get this error without any buildings:

```
Traceback (most recent call last):
  File "/Users/tan_vachiramon/Library/Application Support/Blender/2.78/scripts/addons/blender-osm/__init__.py", line 93, in execute
    return self.importOsm(context, basePath)
  File "/Users/tan_vachiramon/Library/Application Support/Blender/2.78/scripts/addons/blender-osm/__init__.py", line 129, in importOsm
    a.render()
  File "/Users/tan_vachiramon/Library/Application Support/Blender/2.78/scripts/addons/blender-osm/app/__init__.py", line 219, in render
    m.render()
  File "/Users/tan_vachiramon/Library/Application Support/Blender/2.78/scripts/addons/blender-osm/building/manager.py", line 145, in render
    self.renderer.render(building, self.osm)
  File "/Users/tan_vachiramon/Library/Application Support/Blender/2.78/scripts/addons/blender-osm/building/renderer.py", line 102, in render
    self.projectOnTerrain(outline, osm)
  File "/Users/tan_vachiramon/Library/Application Support/Blender/2.78/scripts/addons/blender-osm/building/renderer.py", line 333, in projectOnTerrain
    next( outline.getOuterData(osm) if outline.t is Renderer.multipolygon else outline.getData(osm) )
TypeError: 'NoneType' object is not an iterator

location: <unknown location>:-1
```

<img width="2032" alt="screen shot 2017-07-04 at 10 46 08 am" src="https://user-images.githubusercontent.com/729913/27839510-9aff4bc0-60a6-11e7-93d5-9fbc6dffa503.png">

**Edit:** I've narrowed this issue down to very small region in downtown SF. Importing this region from server with terrain will consistently fail. Unfortunately I don't have enough understanding of the plugin to debug this issue further:
-122.39808,37.79297,-122.39413,37.79812

<img width="1254" alt="screen shot 2017-07-04 at 2 17 21 pm" src="https://user-images.githubusercontent.com/729913/27842992-ffff4c92-60c3-11e7-8e23-6591de9074e0.png">

**Comment by vvoovv** [comment]
Thank you for the bug report!
I'm investigating it right now.

**Comment by vvoovv** [comment]
The problem was due to the wrong mapping of the ship [Santa Rosa](http://www.openstreetmap.org/way/281243360). I fixed it right in the OSM database. A previous mapper used the relation of the _type=multipolygon_ instead of _type=building_.

Please try to import the whole area of your interest again.

Later I'll also fix the problem in the addon code.

**Comment by tanvach** [comment]
Thank you for looking into this! The buildings from above's region have imported properly.

Unfortunately I expanded the region slightly to (-122.51850,37.73380,-122.37413,37.81412) and the import failed again.

**Comment by vvoovv** [comment]
_Slightly_ is probably not the right word, since the resulting OSM file has the size 277 Mb and the number of building in that area is more than 100 thousand.

Anyway I fixed the problem again in the OSM database. This time it was due to the former [Sears Building](http://www.openstreetmap.org/relation/6092952). The same error made by the same mapper as in the first case. I contacted the mapper to point him to the problem.

I successfully imported your area of interest with projection on the terrain. Please download the data from the OSM server and try the import again.

**Comment by vvoovv** [comment]
I'll fix the problem in the addon code with the next public release.

**Comment by tanvach** [comment]
Thanks again for your help. I really appreciate your responsiveness and the plugin is now working great.
