### ISSUE TITLE
Imported doesn't import layers below ground.

### ISSUE THREAD

**Issue by clearbrian** [vvoovv/blender-geo#80]
I'm trying to build a model from underground station information such as London underground.
https://www.openstreetmap.org/#map=19/51.50978/-0.07689
note the platforms are visible.
If you edit you'll see the level is -2
Future update might extract the shape.
Z would be buildheight * -2
height of layer would be 0 or 1 so its flat but still in 3d space
possible?

**Comment by vvoovv** [comment]
Did I understand you correctly that you wanted to place areas tagged with _area=yes_ and _railway=station_ and _layer=-1_ or _layer=-2_ below the ground?

**Comment by clearbrian** [comment]
yes to show the platforms and the railway lines. I understand when you generate level 0,1,2 you make a solid 3d shape with a height.
For below ground we would only need the outline of the shape, as seen in plan with no height.
But placed in -z depending on osm level.
I've attached screen shots of idea in sketchup what it would look like.
If you could assign heights in meter to osm levels that would also be great.
<img width="995" alt="sketchupscreensnapz012" src="https://user-images.githubusercontent.com/132359/28116663-ee9f51c4-6701-11e7-9868-bf76c00ce552.png">
<img width="1121" alt="sketchupscreensnapz013" src="https://user-images.githubusercontent.com/132359/28116706-2dace124-6702-11e7-9ae0-936c50129498.png">

<img width="1554" alt="google chromescreensnapz761" src="https://user-images.githubusercontent.com/132359/28116672-fadc61ac-6701-11e7-8480-daec9148b5fd.png">

**Comment by clearbrian** [comment]
area=yes and railway=station and layer=-1 or layer=-2 below the ground?
just areas and layers. I can edit the generate model in blender later

**Comment by vvoovv** [comment]
I'd suggest to load the desired data separately using Overpass-API, import the data to Blender and position the stations accordingly in Blender.

Open this link for the stations with layer=-1: http://overpass-turbo.eu/s/qmE
There are only 3 of them.
Edit the request for layer=-2 and press Run (only one station is available)

You may use the tag _level_ instead of _layer_.

To download the data press Export -> raw data. Then import the downloaded .osm file to Blender.
